### ISSUE TITLE
Readme Example Not Correct 

### ISSUE THREAD

**Issue by ubaniabalogun** [honerlaw/serverless-fargate-plugin#14]
Opening this because there's actually a slight bug in the README

'Cluster settings' needs to be a list but the example serverless.yaml has it as an object.

The example the readme gives is
```
custom:
  fargate:
    clusterName: Test
    vpc:
      cidr: 10.0.0.0/16
      ....
```

But what actually works is
```
custom:
  fargate:
    - clusterName: Test
       vpc:
        cidr: 10.0.0.0/16
```

Without Cluster settings as a list, the plugin fails with error

```
serverless-fargate-plugin: Cluster will not be deployed due missing options.

  Type Error ---------------------------------------------

  TypeError: options is not iterable
```
