### ISSUE TITLE
Readme not up to date (IClusterOptions needs to be array), Security Groups not autogenerated

### ISSUE THREAD

**Issue by oscarwest** [honerlaw/serverless-fargate-plugin#9]
@gwdp 

Security groups no longer autogenerated, IClusterOptions needs to be an array now and README isn't updated. Alot of new changes don't seem documented in the README.

**Comment by gwdp** [comment]
Hi @oscarwest I recently fixed an issue related to security groups not being generated. PR is open.

Also, related to the new options, all of them seem to be reflected on README. Are you having any issues with it?

**Comment by ubaniabalogun** [comment]
Reopening this because there's actually a slight bug in the README that hasn't been addressed. 

'Cluster settings' needs to be a list but the example serverless.yaml has it as an object. 

The example the readme gives is
```
custom:
  fargate:
    clusterName: Test
    vpc:
      cidr: 10.0.0.0/16
      ....
```

But what actually works is
```
custom:
  fargate:
    - clusterName: Test
       vpc:
        cidr: 10.0.0.0/16
```
